
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    expose:
      - "6000"
    ports:
      - "6000:6000"
    command: -p 6000